#include "ability.h"

struct AbilityData abilities[165] = {
{  0,    "NoAbility", "Report this as an error."},
{  1,       "Stench", "The stench may cause the target to flinch."},
{  2,      "Drizzle", "The Pokémon makes it rain if it appears in battle."},
{  3,  "Speed Boost", "The Pokémon’s Speed stat is gradually boosted."},
{  4, "Battle Armor", "The Pokémon is protected against critical hits."},
{  5,       "Sturdy", "The Pokémon is protected against 1-hit KO attacks."},
{  6,         "Damp", "Prevents combatants from self destructing."},
{  7,       "Limber", "The Pokémon is protected from paralysis."},
{  8,    "Sand Veil", "Boosts the Pokémon’s evasion in a sandstorm."},
{  9,       "Static", "Contact with the Pokémon may cause paralysis."},
{ 10,  "Volt Absorb", "Restores HP if hit by an Electric-type move."},
{ 11, "Water Absorb", "Restores HP if hit by a Water-type move."},
{ 12,    "Oblivious", "Prevents the Pokémon from becoming infatuated."},
{ 13,   "Cloud Nine", "Eliminates the effects of weather."},
{ 14,"Compound Eyes", "The Pokémon’s accuracy is boosted."},
{ 15,     "Insomnia", "Prevents the Pokémon from falling asleep."},
{ 16, "Color Change", "Changes the Pokémon’s type to the foe’s move."},
{ 17,     "Immunity", "Prevents the Pokémon from getting poisoned."},
{ 18,   "Flash Fire", "Powers up Fire-type moves if hit by a fire move."},
{ 19,  "Shield Dust", "Blocks the added effects of attacks taken."},
{ 20,    "Own Tempo", "Prevents the Pokémon from becoming confused."},
{ 21, "Suction Cups", "Negates moves that force switching out."},
{ 22,   "Intimidate", "Lowers the foe’s Attack stat."},
{ 23,   "Shadow Tag", "Prevents the foe from escaping."},
{ 24,   "Rough Skin", "Inflicts damage to the foe on contact."},
{ 25, "Wonder Guard", "Only supereffective moves will hit."},
{ 26,     "Levitate", "Gives full immunity to all Ground-type moves."},
{ 27, "Effect Spore", "Contact may paralyze, poison, or cause sleep."},
{ 28,  "Synchronize", "Passes on a burn, poison, or paralysis to the foe."},
{ 29,   "Clear Body", "Prevents the Pokémon’s stats from being lowered."},
{ 30, "Natural Cure", "All status problems are healed upon switching out."},
{ 31,"Lightning Rod", "The Pokémon draws in all Electric-type moves and then raise Sp.Atk."},
{ 32, "Serene Grace", "Boosts the likelihood of added effects appearing."},
{ 33,   "Swift Swim", "Boosts the Pokémon’s Speed in rain."},
{ 34,  "Chlorophyll", "Boosts the Pokémon’s Speed in sunshine."},
{ 35,   "Illuminate", "Raises the likelihood of meeting wild Pokémon."},
{ 36,        "Trace", "The Pokémon copies a foe's Ability."},
{ 37,   "Huge Power", "Raises the Pokémon’s Attack stat."},
{ 38, "Poison Point", "Contact with the Pokémon may poison the foe."},
{ 39,  "Inner Focus", "The Pokémon is protected from flinching."},
{ 40,  "Magma Armor", "Prevents the Pokémon from becoming frozen."},
{ 41,   "Water Veil", "Prevents the Pokémon from getting a burn."},
{ 42,  "Magnet Pull", "Prevents Steel-type Pokémon from escaping."},
{ 43,   "Soundproof", "Gives full immunity to all sound-based moves."},
{ 44,    "Rain Dish", "The Pokémon gradually recovers HP in rain."},
{ 45,  "Sand Stream", "The Pokémon summons a sandstorm in battle."},
{ 46,     "Pressure", "The Pokémon raises the foe’s PP usage."},
{ 47,    "Thick Fat", "Raises resistance to Fire- and Ice-type moves."},
{ 48,   "Early Bird", "The Pokémon awakens quickly from sleep."},
{ 49,   "Flame Body", "Contact with the Pokémon may burn the foe."},
{ 50,     "Run Away", "Enables sure getaway from wild Pokémon."},
{ 51,     "Keen Eye", "Prevents the Pokémon from losing accuracy."},
{ 52, "Hyper Cutter", "Prevents the Attack stat from being lowered."},
{ 53,       "Pickup", "The Pokémon may pick up items."},
{ 54,       "Truant", "The Pokémon can't attack on consecutive turns."},
{ 55,       "Hustle", "Boosts the Attack stat, but lowers accuracy."},
{ 56,   "Cute Charm", "Contact with the Pokémon may cause infatuation."},
{ 57,         "Plus", "Boosts Sp. Atk if another Pokémon has Minus."},
{ 58,        "Minus", "Boosts Sp. Atk if another Pokémon has Plus."},
{ 59,     "Forecast", "Transforms with the weather."},
{ 60,  "Sticky Hold", "Protects the Pokémon from item theft."},
{ 61,    "Shed Skin", "The Pokémon may heal its own status problems."},
{ 62,         "Guts", "Boosts Attack if there is a status problem."},
{ 63, "Marvel Scale", "Boosts Defense if there is a status problem."},
{ 64,  "Liquid Ooze", "Inflicts damage on foes using any draining move."},
{ 65,     "Overgrow", "Powers up Grass-type moves in a pinch."},
{ 66,        "Blaze", "Powers up Fire-type moves in a pinch."},
{ 67,      "Torrent", "Powers up Water-type moves in a pinch."},
{ 68,        "Swarm", "Powers up Bug-type moves in a pinch."},
{ 69,    "Rock Head", "Protects the Pokémon from recoil damage."},
{ 70,      "Drought", "The Pokémon makes it sunny if it is in battle."},
{ 71,   "Arena Trap", "Prevents the foe from fleeing."},
{ 72, "Vital Spirit", "Prevents the Pokémon from falling asleep."},
{ 73,  "White Smoke", "Prevents the Pokémon’s stats from being lowered."},
{ 74,   "Pure Power", "Boosts the power of physical attacks."},
{ 75,  "Shell Armor", "The Pokémon is protected against critical hits."},
{ 76,     "Air Lock", "Eliminates the effects of weather."},
{ 77, "Tangled Feet", "Raises evasion if the Pokémon is confused."},
{ 78,  "Motor Drive", "Raises Speed if hit by an Electric-type move."},
{ 79,      "Rivalry", "Raises Attack if the foe is of the same gender."},
{ 80,    "Steadfast", "Raises Speed each time the Pokémon flinches."},
{ 81,   "Snow Cloak", "Raises evasion in a hailstorm."},
{ 82,     "Gluttony", "Encourages the early use of a held Berry."},
{ 83,  "Anger Point", "Raises Attack upon taking a critical hit."},
{ 84,     "Unburden", "Raises Speed if a held item is used."},
{ 85,    "Heatproof", "Weakens the power of Fire-type moves."},
{ 86,       "Simple", "The Pokémon is prone to wild stat changes."},
{ 87,     "Dry Skin", "Reduces HP if it is hot. Water restores HP."},
{ 88,     "Download", "Adjusts power according to the foe’s lowest defensive stat."},
{ 89,    "Iron Fist", "Boosts the power of punching moves."},
{ 90,  "Poison Heal", "Restores HP if the Pokémon is poisoned."},
{ 91, "Adaptability", "Powers up moves of the same type."},
{ 92,   "Skill Link", "Increases the frequency of multi-strike moves."},
{ 93,    "Hydration", "Heals status problems if it is raining."},
{ 94,  "Solar Power", "Boosts Sp. Atk, but lowers HP in sunshine."},
{ 95,   "Quick Feet", "Boosts Speed if there is a status problem."},
{ 96,    "Normalize", "All the Pokémon’s moves become the Normal type."},
{ 97,       "Sniper", "Powers up moves if they become critical hits."},
{ 98,  "Magic Guard", "The Pokémon only takes damage from attacks."},
{ 99,     "No Guard", "Ensures the Pokémon and its foe’s attacks land."},
{100,        "Stall", "The Pokémon moves after even slower foes."},
{101,   "Technician", "Powers up the Pokémon’s weaker moves."},
{102,   "Leaf Guard", "Prevents status problems in sunny weather."},
{103,        "Klutz", "The Pokémon can’t use any held items."},
{104, "Mold Breaker", "Moves can be used regardless of Abilities."},
{105,   "Super Luck", "Heightens the critical-hit ratios of moves."},
{106,    "Aftermath", "Damages the foe landing the finishing hit."},
{107, "Anticipation", "Senses the foe’s dangerous moves."},
{108,     "Forewarn", "Determines what moves the foe has."},
{109,      "Unaware", "Ignores any change in stats by the foe."},
{110,  "Tinted Lens", "Powers up “not very effective” moves."},
{111,       "Filter", "Powers down supereffective moves."},
{112,   "Slow Start", "Temporarily halves Attack and Speed."},
{113,      "Scrappy", "Enables moves to hit Ghost-type foes."},
{114,  "Storm Drain", "The Pokémon draws in all Water-type moves."},
{115,     "Ice Body", "The Pokémon regains HP in a hailstorm."},
{116,   "Solid Rock", "Powers down supereffective moves."},
{117, "Snow Warning", "The Pokémon summons a hailstorm in battle."},
{118, "Honey Gather", "The Pokémon may gather Honey from somewhere."},
{119,        "Frisk", "The Pokémon can check the foe’s held item."},
{120,     "Reckless", "Powers up moves that have recoil damage."},
{121,    "Multitype", "Changes type to match the held Plate."},
{122,  "Flower Gift", "Powers up party Pokémon when it is sunny."},
{123,   "Bad Dreams", "Reduces a sleeping foe’s HP."},
{124,   "Pickpocket", "Steals attacking Pokémon's held item on contact."},
{125,  "Sheer Force", "Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects."},
{126,     "Contrary", "Inverts stat modifiers."},
{127,      "Unnerve", "Prevents opposing Pokémon from eating held Berries."},
{128,      "Defiant", "Raises Attack two stages upon having any stat lowered."},
{129,    "Defeatist", "Halves Attack and Special Attack below 50% HP."},
{130,  "Cursed Body", "Has a 30% chance of Disabling any move that hits the Pokémon."},
{131,       "Healer", "Has a 30% chance of curing each adjacent ally of any major status ailment after each turn."},
{132, "Friend Guard", "Decreases damage inflicted against ally Pokémon."},
{133,   "Weak Armor", "Raises Speed and lowers Defense by one stage each upon being hit by any move."},
{134,  "Heavy Metal", "Doubles the Pokémon's weight."},
{135,  "Light Metal", "Halves the Pokémon's weight."},
{136,   "Multiscale", "Halves damage taken from full HP."},
{137,  "Toxic Boost", "Increases Attack to 1.5× when poisoned."},
{138,  "Flare Boost", "Increases Special Attack to 1.5× when burned."},
{139,      "Harvest", "Restores any held Berry after the turn on which it is used."},
{140,    "Telepathy", "Protects against damaging moves from friendly Pokémon."},
{141,        "Moody", "Raises a random stat two stages and lowers another one stage after each turn."},
{142,     "Overcoat", "Protects against damage from weather."},
{143, "Poison Touch", "Has a 30% chance of poisoning Pokémon upon contact when attacking."},
{144,  "Regenerator", "Heals for 1/3 max HP upon leaving battle."},
{145,    "Big Pecks", "Protects the Pokémon from Defense-lowering attacks."},
{146,    "Sand Rush", "Doubles Speed during a sandstorm."},
{147,  "Wonder Skin", "Has a 50% chance of protecting against non-damaging moves that inflict major status ailments."},
{148,     "Analytic", "Strengthens moves when moving last."},
{149,     "Illusion", "Takes the appearance of the last conscious party Pokémon upon being sent out until hit by a damaging move."},
{150,     "Imposter", "Transforms upon entering battle."},
{151,  "Infiltrator", "Ignores Light Screen, Reflect, and Safeguard."},
{152,        "Mummy", "Contact with this Pokémon spreads this Ability."},
{153,        "Moxie", "Raises Attack one stage upon KOing a Pokémon."},
{154,    "Justified", "Raises Attack when hit by Dark-type moves."},
{155,      "Rattled", "Raises Speed one stage upon being hit by a Dark, Ghost, or Bug move."},
{156, "Magic Bounce", "Reflects most non-damaging moves back at their user."},
{157,   "Sap Sipper", "Absorbs Grass moves, raising Attack one stage."},
{158,    "Prankster", "Raises non-damaging moves' priority by one stage."},
{159,   "Sand Force", "Strengthens Rock, Ground, and Steel moves to 1.3× their power during a sandstorm."},
{160,   "Iron Barbs", "Damages attacking Pokémon for 1/8 their max HP on contact."},
{161,     "Zen Mode", "Changes the Pokémon's shape when HP is halved."},
{162, "Victory Star", "Raises moves' accuracy to 1.1× for friendly Pokémon."},
{163,   "Turboblaze", "Moves can be used regardless of Abilities."},
{164,     "Teravolt", "Moves can be used regardless of Abilities."}
};
